<a href="https://colab.research.google.com/github/skylarsepanek/Stats_Sepanek/blob/main/Sepanek_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#STATS Lab 3 

#loops

In [1]:
for i in range (10): #up to but excluding chosen number
  print (i)

0
1
2
3
4
5
6
7
8
9


In [2]:
for i in range (5,8): #giving range
  print (i)

5
6
7


In [3]:
for i in range(3): #gives numbers in that range but exluding
    print("Test Number: ",i)


Test Number:  0
Test Number:  1
Test Number:  2


#functions


In [5]:
def square(x): #defing what square is
  return x**2

In [6]:
square(5) #telling it to square 5

25

In [8]:
square(1234567890) 

1524157875019052100

In [10]:
square(square(5))

625

In [11]:
square(square(square(5)))


390625

In [12]:
def add_two(x): #defining adding two
  return x+2

In [13]:
add_two(5)

7

In [14]:
square(add_two(5))

49

#logical branching

In [17]:
choice = "apple"

In [25]:
if choice == "apple":

    print("You choose apples.")
    

else:
    
    print("You did not choose apples.")

You choose apples.


In [26]:
choice = "orange"

In [21]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [22]:
if choice == "apple":

    print("You choose apples.")

elif choice == "orange":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


# User Input

In [29]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): orange


In [28]:
choice

'orange'

#speed test

In [31]:
import numpy as np


In [32]:
np.random.permutation(52) 

array([11, 37, 44, 23, 21,  4, 20, 29, 18, 36, 41, 42, 19, 43, 22, 39, 48,
       50, 10, 13,  6, 16, 32, 17, 33, 14,  5,  3,  7, 12, 46, 28,  2, 49,
       51,  1,  8, 25, 38, 26, 31,  9, 40, 27, 47, 45, 30, 34, 35,  0, 15,
       24])

In [33]:
cards = np.random.permutation(52)

In [34]:
cards[0]

40

In [35]:
cards[11]

36

In [36]:
cards[37]

5

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [37]:
np.arange(52).reshape(4,13) #gives rows and colums

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [38]:
np.arange(52).reshape(4,13)%13     #this is modulo

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [39]:
np.arange(52).reshape(4,13)//13      #floor division


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [40]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [41]:
suits

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [42]:
suits[0]

'Clubs'

In [45]:
names[0]

'Ace'

In [43]:
names[1]

'Two'

In [46]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [47]:
card_name(0) #names card on picture

'Ace of Clubs'

In [48]:
card_name(3) #names 3rd card

'Four of Clubs'

In [49]:
card_name(29) #names 29th card

'Four of Hearts'

In [50]:
card_name(51) #names 51st card

'King of Diamonds'

In [51]:
cards = np.random.permutation(52)

In [52]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [53]:
top_of_deck,second_card_in_deck,last_card_in_deck


('Queen of Clubs', 'Six of Hearts', 'Three of Hearts')

In [54]:
for i in range(5): #gives 5 random cards from deck
    print(card_name(cards[i]))

Queen of Clubs
Six of Hearts
Eight of Clubs
Ten of Diamonds
Two of Diamonds


In [55]:
for i in range(10): #gives 10 random cards from deck
    print(card_name(cards[i]))

Queen of Clubs
Six of Hearts
Eight of Clubs
Ten of Diamonds
Two of Diamonds
Four of Hearts
Ace of Diamonds
Ten of Spades
Ten of Hearts
Seven of Diamonds


In [56]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"  #impots card images
card_url_tail = ".png"

In [57]:
suit = ['k','p','s','l']       
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [58]:
i = np.random.randint(4)
j = np.random.randint(13)

In [59]:
i,j   #suit, then card

(1, 9)

In [60]:
suit[i]

'p'

In [61]:
card[j]

'10'

In [68]:
from IPython.core.display import display, HTML

In [66]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [63]:
img = card_url_head + suit[i]+card[j] + card_url_tail

In [69]:
show_img(img)

In [71]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [72]:
card_image(3)

'k4'

In [73]:
img = card_url_head + card_image(3) + card_url_tail

In [74]:
show_img(img)

In [75]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)